const particles =
  'trail.(heart|angry|magic|fun|cloud|wmagic|ender|green|spark|flame|white|note|snow|water|lava|crit|smoke|spell|enchant|splash|slime|snowball|pop|rainbow|breath|endrod|damage|totem)'

const donateInGroups = [
  {},
  {
    default: { name: 'без привилегий', val: 0, cost: 0 },
    vip: { name: 'VIP', val: 1, cost: 70, perm: 'vip', type: 'group' },
    vipp: {
      name: 'VIP+',
      val: 2,
      cost: 120,
      perm: 'vipp',
      type: 'group',
    },
    mvp: { name: 'MVP', val: 3, cost: 250, perm: 'mvp', type: 'group' },
    mvpp: {
      name: 'MVP+',
      val: 4,
      cost: 500,
      perm: 'mvpp',
      type: 'group',
    },
  },
  {
    default: { name: 'без привилегий', val: 0, cost: 0 },
    fly: { name: 'Флай', val: 1, cost: 15, perm: 'fly', type: 'group' },
    _vip: { name: 'Вип', val: 2, cost: 50, perm: '_vip', type: 'group' },
    premium: {
      name: 'Премиум',
      val: 3,
      cost: 80,
      perm: 'premium',
      type: 'group',
    },
    crative: {
      name: 'Креатив',
      val: 4,
      cost: 120,
      perm: 'creative',
      type: 'group',
    },
    moder: {
      name: 'Модер',
      val: 5,
      cost: 200,
      perm: 'moder',
      type: 'group',
    },
    stmoder: {
      name: 'Ст.Модер',
      val: 6,
      cost: 250,
      perm: 'stmoder',
      type: 'group',
    },
    admin: {
      name: 'Админ',
      val: 7,
      cost: 350,
      perm: 'admin',
      type: 'group',
    },
    gladmin: {
      name: 'Гл.Админ',
      val: 8,
      cost: 450,
      perm: 'gladmin',
      type: 'group',
    },
    owner: {
      name: 'Владелец',
      val: 9,
      cost: 600,
      perm: 'owner',
      type: 'group',
    },
    lord: {
      name: 'Повелитель',
      val: 10,
      cost: 700,
      perm: 'lord',
      type: 'group',
    },
    god: {
      name: 'Божество',
      val: 11,
      cost: 1000,
      perm: 'god',
      type: 'group',
    },
    support: {
      name: 'Support',
      val: 12,
      cost: 2000,
      perm: 'support',
      type: 'group',
    },
    dev: { name: 'Dev', val: 13, cost: 3000, perm: 'dev', type: 'group' },
  },
  {
    default: { name: 'Нет доступа к серверу', val: 0, cost: 0 },
    whitelist: {
      name: 'Доступ к серверу',
      val: 1,
      cost: 200,
      perm: 'rainfall.whitelist',
      type: 'whitelist',
    },
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    default: { name: '..', val: 0, cost: 0 },
    particles: {
      name: 'Частицы',
      val: 1,
      cost: 100,
      perm: particles,
      type: 'permission',
    },
    blocks: {
      name: 'Блоки',
      val: 2,
      cost: 100,
      perm: 'trail.blocks',
      type: 'permission',
    },
    rains: {
      name: 'Дождевые эффекты',
      val: 3,
      cost: 100,
      perm: 'trail.rains',
      type: 'permission',
    },
    wings: {
      name: 'Крылья',
      val: 4,
      cost: 100,
      perm: 'trail.wings',
      type: 'permission',
    },
  },
  {
    default: { name: '...', val: 0, cost: 0 },
    symbols: {
      name: 'Символы',
      val: 1,
      cost: 60,
      perm: 'tags.symbols',
      type: 'permission',
    },
    smiles: {
      name: 'Смайлы',
      val: 2,
      cost: 60,
      perm: 'tags.smiles',
      type: 'permission',
    },
    standart: {
      name: 'Стандарт',
      val: 3,
      cost: 60,
      perm: 'tags.default',
      type: 'permission',
    },
    foodnanimals: {
      name: 'ЕДА/ЖИВНОСТЬ',
      val: 4,
      cost: 60,
      perm: 'tags.foodnanimals',
      type: 'permission',
    },
    names: {
      name: 'Имена',
      val: 5,
      cost: 60,
      perm: 'tags.names',
      type: 'permission',
    },
  },
  {
    default: { name: '...', val: 0, cost: 0 },
    case1: {
      name: 'Кейс PROMISED-LAND x5',
      val: 1,
      cost: 75,
      perm: 'galactic.5',
      type: 'case',
    },
    case10: {
      name: 'Кейс PROMISED-LAND x10',
      val: 2,
      cost: 140,
      perm: 'galactic.10',
      type: 'case',
    },
    case25: {
      name: 'Кейс PROMISED-LAND x25',
      val: 3,
      cost: 300,
      perm: 'galactic.25',
      type: 'case',
    },
  },
  {
    default: { name: '...', val: 0, cost: 0 },
    unban: {
      name: 'РАЗБАН НА ВСЕХ СЕРВЕРАХ',
      val: 1,
      cost: 299,
      perm: 'unban',
      type: 'unban',
    },
  },
]

module.exports = donateInGroups
